version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB: data_kepegawaian
  app:
    image: test-jm
    ports:
      - 8080:3000